spring:
  application:
    name: server-status-tracking
  datasource:
    url: jdbc:postgresql://localhost:5432/serverstatus
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true